### ISSUE TITLE
We must agree on a naming convention

### ISSUE THREAD

**Issue by mohgalal** [Ali-El-Sayed/Ryady#5]
1. Using _camelCase_ for branch names is not a common practice and can reduce readability compared to using **hyphens** or underscores.
2. Use **lowercase** for branch names.
3. **Avoid overly specific names**, means don’t write loginScreen❌ write login✅ without screen

If you want to use _camelCase_ it’s fine, but you have to be aligned as a team not some of you use _camelCase_ and others **hyphens**

Right Example: **_feature/login-ui_**

**Comment by moahamdhussein** [comment]
solved this issue and thank you for your support
